/**
 * Uniquely identifies a particular cargo. Automatically generated by the application.
 */
import { IValueObject } from '../../types/value-object.interface';
import { Validate } from '../../helpers/validate.helper';

export class TrackingId implements IValueObject<TrackingId> {
  private readonly id: string;

  constructor(id: string) {
    Validate.notNil(id);
    this.id = id;
  }

  /**
   * @return String representation of this tracking id.
   */
  public idString(): string {
    return this.id;
  }

  public equals(o: object): boolean {
    if (this === o) return true;
    if (!o || !(o instanceof TrackingId)) return false;

    const other: TrackingId = o as TrackingId;

    return this.sameValueAs(other);
  }

  public sameValueAs(other: TrackingId): boolean {
    return other != null && this.id === other.id;
  }

  public toString(): string {
    return this.id;
  }
}
